#!/usr/bin/env node
/**
 * Consensus pass runner — reads h22-torques-flat.jsonl, runs consensus
 * algorithm, emits h22-torques.jsonl + h22-torques-disputed.jsonl +
 * consensus-report.md.
 *
 * Usage:
 *   node src/torque-runner/run-consensus.ts [--input <path>] [--output-dir <path>]
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { runConsensusPass } from "../torque-consensus/consensus.js";
import type { FlatRow, ConsensusReport } from "../torque-consensus/types.js";

interface CliOptions {
  input: string;
  outputDir: string;
}

function parseArgs(): CliOptions {
  const args = process.argv.slice(2);
  let input = "research/raw-data/torque-specs/h22-torques-flat.jsonl";
  let outputDir = "research/raw-data/torque-specs";

  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--input" && i + 1 < args.length) {
      input = args[++i];
    } else if (args[i] === "--output-dir" && i + 1 < args.length) {
      outputDir = args[++i];
    } else if (args[i] === "--help" || args[i] === "-h") {
      console.log("Usage: run-consensus.ts [--input <path>] [--output-dir <path>]");
      process.exit(0);
    }
  }

  return {
    input: resolve(input),
    outputDir: resolve(outputDir),
  };
}

function readFlatRows(filePath: string): FlatRow[] {
  if (!existsSync(filePath)) {
    console.error(`Error: input file not found: ${filePath}`);
    process.exit(1);
  }

  const content = readFileSync(filePath, "utf-8");
  const lines = content.trim().split("\n").filter((l) => l.trim() !== "");

  if (lines.length === 0) {
    console.warn("Warning: input file is empty — no rows to process.");
    return [];
  }

  const rows: FlatRow[] = [];
  for (const line of lines) {
    try {
      const parsed = JSON.parse(line);
      // Validate required fields
      if (!parsed.id || !parsed.invocation_id || parsed.page === undefined) {
        console.warn(`Skipping malformed row (missing id/invocation_id/page): ${line.substring(0, 80)}...`);
        continue;
      }
      rows.push(parsed as FlatRow);
    } catch (e) {
      console.warn(`Skipping unparseable line: ${line.substring(0, 80)}...`);
    }
  }

  return rows;
}

function formatMarkdown(report: ConsensusReport): string {
  const lines: string[] = [];

  lines.push("# Consensus Report — h22-torques.jsonl");
  lines.push("");
  lines.push("> Auto-generated by `run-consensus.ts`. Do not edit manually.");
  lines.push("");

  // Summary section
  lines.push("## Summary");
  lines.push("");
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Total pages processed | ${report.summary.total_pages} |`);
  lines.push(`| Total fasteners seen | ${report.summary.total_fasteners} |`);
  lines.push(`| Consensus rows emitted | ${report.summary.total_consensus} |`);
  lines.push(`| Disputed rows | ${report.summary.total_disputed} |`);
  lines.push(`| Single-source rows | ${report.summary.total_single_source} |`);
  lines.push(`| Average vote strength | ${report.summary.avg_vote_strength.toFixed(3)} |`);
  lines.push(`| Models contributing | ${report.summary.models_contributing.join(", ") || "(none)"} |`);
  lines.push("");

  // Per-page breakdown
  if (report.pages.length > 0) {
    lines.push("## Per-Page Breakdown");
    lines.push("");
    lines.push("| Manual | Page | Fasteners | Consensus | Disputed | Avg Vote Strength | Models |");
    lines.push("|--------|------|-----------|-----------|----------|-------------------|--------|");

    for (const ps of report.pages) {
      lines.push(
        `| ${ps.manual} | ${ps.page} | ${ps.total_fasteners} | ${ps.consensus_count} | ${ps.disputed_count} | ${ps.avg_vote_strength.toFixed(3)} | ${ps.models_contributing.join(", ") || "-"} |`
      );
    }
    lines.push("");
  }

  // Vote strength distribution
  if (report.pages.length > 0) {
    lines.push("## Vote Strength Distribution");
    lines.push("");
    lines.push("| Range | Count |");
    lines.push("|-------|-------|");

    const buckets = { "1.000": 0, "0.750–0.999": 0, "0.500–0.749": 0, "<0.500": 0 };
    for (const ps of report.pages) {
      if (ps.avg_vote_strength >= 1.0) buckets["1.000"]++;
      else if (ps.avg_vote_strength >= 0.75) buckets["0.750–0.999"]++;
      else if (ps.avg_vote_strength >= 0.5) buckets["0.500–0.749"]++;
      else buckets["<0.500"]++;
    }

    for (const [range, count] of Object.entries(buckets)) {
      lines.push(`| ${range} | ${count} |`);
    }
    lines.push("");
  }

  // Disputed rows summary
  if (report.summary.total_disputed > 0) {
    lines.push("## Disputed Rows");
    lines.push("");
    lines.push(`${report.summary.total_disputed} fastener groups had no majority consensus.`);
    lines.push("These are in `h22-torques-disputed.jsonl` for manual resolution.");
    lines.push("");
  }

  return lines.join("\n");
}

function main(): void {
  const opts = parseArgs();

  console.log(`Reading flat rows from: ${opts.input}`);
  const flatRows = readFlatRows(opts.input);
  console.log(`Loaded ${flatRows.length} flat rows.`);

  if (flatRows.length === 0) {
    console.warn("No rows to process. Writing empty output files.");

    // Ensure output directory exists
    if (!existsSync(opts.outputDir)) {
      mkdirSync(opts.outputDir, { recursive: true });
    }

    writeFileSync(resolve(opts.outputDir, "h22-torques.jsonl"), "", "utf-8");
    writeFileSync(resolve(opts.outputDir, "h22-torques-disputed.jsonl"), "", "utf-8");
    writeFileSync(resolve(opts.outputDir, "consensus-report.md"), "# Consensus Report\n\nNo data to process.\n", "utf-8");

    console.log("Empty output files written.");
    return;
  }

  console.log("Running consensus pass...");
  const { consensusRows, disputedRows, report } = runConsensusPass(flatRows);

  console.log(`Consensus: ${consensusRows.length} rows, Disputed: ${disputedRows.length} rows`);

  // Ensure output directory exists
  if (!existsSync(opts.outputDir)) {
    mkdirSync(opts.outputDir, { recursive: true });
  }

  // Write h22-torques.jsonl
  const torquesPath = resolve(opts.outputDir, "h22-torques.jsonl");
  writeFileSync(torquesPath, consensusRows.map((r) => JSON.stringify(r)).join("\n") + (consensusRows.length > 0 ? "\n" : ""), "utf-8");
  console.log(`Wrote ${consensusRows.length} consensus rows to ${torquesPath}`);

  // Write h22-torques-disputed.jsonl
  const disputedPath = resolve(opts.outputDir, "h22-torques-disputed.jsonl");
  writeFileSync(disputedPath, disputedRows.map((r) => JSON.stringify(r)).join("\n") + (disputedRows.length > 0 ? "\n" : ""), "utf-8");
  console.log(`Wrote ${disputedRows.length} disputed rows to ${disputedPath}`);

  // Write consensus-report.md
  const reportPath = resolve(opts.outputDir, "consensus-report.md");
  writeFileSync(reportPath, formatMarkdown(report), "utf-8");
  console.log(`Wrote consensus report to ${reportPath}`);

  // Print summary
  console.log("");
  console.log("=== Consensus Summary ===");
  console.log(`Pages processed:       ${report.summary.total_pages}`);
  console.log(`Fasteners seen:        ${report.summary.total_fasteners}`);
  console.log(`Consensus rows:        ${report.summary.total_consensus}`);
  console.log(`Disputed rows:         ${report.summary.total_disputed}`);
  console.log(`Single-source rows:    ${report.summary.total_single_source}`);
  console.log(`Avg vote strength:     ${report.summary.avg_vote_strength.toFixed(3)}`);
  console.log(`Models contributing:   ${report.summary.models_contributing.join(", ") || "(none)"}`);
}

main();
